name: Continuous Intergration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
    
    - name: Run build
      run: swift build -v
      
    - name: Run test
      run: swift test -v
